import "./globals.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins, Barlow, Kanit } from "next/font/google";

let logoFont = "../../public/assets/fonts/nulshock-bd.otf" ;
let pageFont = "../../public/assets/fonts/Kanit-Bold.ttf" ;
const berlin = localFont({
  // src: [
  //   {
  //     path: "../../public/assets/fonts/berlin_sans_fb_demi_bold-webfont.woff",
  //     weight: "normal",
  //     style: "normal",
  //   },
  //   {
  //     path: "../../public/assets/fonts/berlin_sans_fb_demi_bold-webfont.woff2",
  //     weight: "normal",
  //     style: "normal",
  //   },
  // ],
  src: [
    {
      path:  "../../public/assets/fonts/nulshock-bd.otf",
      weight: "normal",
      style: "normal",
    }
  ],
  variable: "--tg-berlin-font-family",
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--tg-body-font-family",
});

const bodyFont = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Kanit-Bold.ttf",
      weight: "normal",
      style: "normal",
    }
  ],
  variable: "--tg-body-font-family"
});

const heeaderFont = localFont({
  src: [
    {
      path:"../../public/assets/fonts/Kanit-Bold.ttf",
      weight: "normal",
      style: "normal",
    }
  ],
  variable: "--tg-heading-font-family"
});

const barlow = Barlow({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--tg-heading-font-family",
});

export const metadata: Metadata = {
  title: "G2G168SA - Sport Betting and Casino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${bodyFont.variable} ${poppins.variable} ${heeaderFont.variable} ${berlin.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
